### ISSUE TITLE
Games related bugs!

### ISSUE THREAD

**Issue by bsko** [goodfootclub/specs#39]
1) I can create a game in past. Also i can invite players there and they are allowed to accept invitation.

2) If i create a game that starts in ~1.5 hour - it won't be returned from /games/my/ service. (Could be timezone issue, should be discussed)

3) Players in game should be sorted by rsvp status (can fix it on client, but from my point of view, it should be done on BE)

4) If i'm creating a game with team as a team manager - i won't be added to game roaster. It will be empty.

**Comment by bsko** [comment]
1) added validation on fronend. Should i add some message notification there why yser cannot create a game? or something?
2) I think its FE issue. Wrong date was sent on game creation. Fixed.
Others are BE issues & questions.

**Comment by Igonato** [comment]
1. This is overengineering IMO. For example, Google calendar allows adding events in the past. I'm not exactly sure what the possible use-case would be but adding games to the past doesn't break anything, so preventing it seems to be extra complexity. I'm going to vote nay on it

2. Yep, FE issue, fixed.

3. It was like that in the past and we switched the ordering by datetime. We can add filtering UI that would allow specifying the ordering. Would be cool to have a site-wide universal filter component.

4. If you are a manager and not a player on the team this is the correct behavior. I just pushed automatic adding as a captain for the creator of a team when a team is created, so this shouldn't be so much of an issue

**Comment by donlafranchi** [comment]
1. I'm not worried about users who create games in the past.  When this is fully built out the only ones creating games will be "Leagues" (except for pickup games).
2. Games not showing up if they are created within a couple hours are possibly not displaying because we decided to keep the my games list clean by only showing games occurring in the future.  Not sure what the time cutoff off for "future" is. 
3.  As far as I can tell players are sorted by RSVP status for each game. (Ignat I believe you are thinking about game sorting. Games were sorted by RSVP status but that placed games out of date order.)
4. Managers are not added to the player roster. It's kind of funky but I don't mind if it is this way for now.  I don't like how the manager and player games are scheduled though.  Either way it isn't critical right now.

**Comment by Igonato** [comment]
I'll double check this

**Comment by Igonato** [comment]
3. Pardon. Misunderstanding on my part, indeed. Fixed!
